<!--
/**
 * PartyLite_Microsites
 *
 * @category    PartyLite
 * @package     PartyLite_Microsites
 * @copyright   Copyright (c) 2018 Optaros
 * @author      Casian Daniel Suciu <dsuciu@optaros.com>
 */
 -->


<div id="back-to-top">
    <span class="back-top"><?php /* @escapeNotVerified */ echo __("Back to top") ?></span>
</div>

<script>
    require(['jquery'], function ($) {
        $("#back-to-top").click(function() {
            $("html, body").animate({ scrollTop: 0 }, "slow");
            return false;
        });
    });
</script>
